name = "ImsBacck"
author = "PepXter"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b59296d9a4cf4e8afdcee865fd794c791f67379d73844c4d08e56ce4dd39783e"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
