name = "ImsBacck"
author = "PepXter"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71f2a59806721e64ccc7952e7bd820dc5e4edd5b538d6f1c2921a6bc6bd60951"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
