name = "ImsBacck"
author = "PepXter"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cdf9decc417c9891a09c1ed8f34072a96f7f3831b7fc69f236ef1c5f6fa1dd0"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
